package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

type SetupConfig struct {
	Consul   string
	Config   string
	Template string
	ServiceDescription
}

func (sc SetupConfig) ConfigIn() string {
	return sc.Config + ".tpl"
}

func (sc SetupConfig) ConfigOut() string {
	return sc.Config
}

func SetupService(cfg SetupConfig) error {
	f, err := os.OpenFile(cfg.ConfigIn(), os.O_RDWR|os.O_TRUNC|os.O_CREATE, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	cfg.ServiceDescription.Image = fmt.Sprintf(`{{if key "%s"}}{{key "%s"}}{{else}}{{key "%s"}}{{end}}`,
		cfg.ServiceDescription.NodeDeploy(),
		cfg.ServiceDescription.NodeDeploy(),
		cfg.ServiceDescription.AppCurrent())

	err = cfg.ServiceDescription.SaveTo(f)
	if err != nil {
		return err
	}

	return saveConsulTemplate(cfg)
}

func saveConsulTemplate(cfg SetupConfig) error {
	tpl := fmt.Sprintf(`# Generated by sheepit
template {
	source = "%s"
	destination = "%s"
	command = "sheepit service -f %s"
}`, cfg.ConfigIn(), cfg.ConfigOut(), cfg.ConfigOut())

	return ioutil.WriteFile(cfg.Template, []byte(tpl), 0644)
}
